---
- name: Download DNF packages with dependencies
  hosts: HostSvr
  become: true
  tasks:
    - name: Ensure the download directory exists
      file:
        path: /var/www/html/dnfrepo
        state: directory
        mode: '0755'

    - name: Download epel-release
      dnf:
        name: 
          - epel-release
        state: present

    - name: Update DNF package information
      dnf:
        update_cache: yes

    - name: Download the package and dependencies
      dnf:
        name: 
          - yum-utils
          - createrepo
          - httpd
          - ansible
        state: present
        download_only: yes
        download_dir: /var/www/html/dnfrepo
      register: dnf_download

    - name: Show downloaded files
      debug:
        var: dnf_download.results

    - name: Create DNF repository
      command: createrepo /var/www/html/dnfrepo

    - name: Start and enable HTTPD service
      service:
        name: httpd
        state: started
        enabled: yes


