---
- name: Download DNF packages with dependencies
  hosts: HostSvr
  become: true
  tasks:
    - name: Ensure the download directory exists
      file:
        path: /var/www/html/dnfrepo
        state: directory
        mode: '0755'

    # - name: Check if download directory exists
    #   stat:
    #     path: /var/www/html/dnfrepo
    #   register: dnfrepo_dir

    # - debug:
    #     var: dnfrepo_dir

    - name: Download epel-release
      dnf:
        name: 
          - epel-release
        state: present
        update_cache: yes

    # - name: Download the package and dependencies
    #   dnf:
    #     name: 
    #       - yum-utils
    #       - createrepo
    #       - httpd
    #       - ansible
    #     state: present
    #     download_only: yes
    #     download_dir: /var/www/html/dnfrepo
    #   register: dnf_download

    - name: Download DNF package
      command: dnf download --resolve --alldeps --downloadonly --downloaddir /var/www/html/dnfrepo yum-utils createrepo httpd ansible
      register: dnf_download
    
    - name: Show downloaded files
      debug:
        var: dnf_download

    - name: Create DNF repository
      command: createrepo /var/www/html/dnfrepo

    - name: Start and enable HTTPD service
      service:
        name: httpd
        state: started
        enabled: yes
